### ISSUE TITLE
add new field precio to vid model 

### ISSUE THREAD

**Issue by Japoivvb** [FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS#4]
1. add double precio attribute to vid model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by FranS111** [comment]
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/2b2820c0-f915-4b2a-9542-42083939ea87)
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/1fbb9e55-0b25-4591-8b47-775f635b8e11)
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/5fb953bf-010f-42da-b9ae-9db47ec775e5)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
