### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by FranS111** [comment]
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/9a8b9ab6-b375-4ad9-9a74-0e06561b516b)
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/0f98e085-ea8a-491a-922e-a25658101eff)
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/9549506e-51eb-4c6f-b719-d7499eaba078)
![image](https://github.com/FranS111/DAM2T-M06-UF2-P2-Viticulture_FranS/assets/117041052/367744a0-51de-43a7-8e8d-bbc8fabd9e70)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
well done, although your approach was very different, linking objects by id and removing all models ... you built the collection as related tables instead embedded documents one in another
